<?php

namespace model\entities\proxy\__CG__\model\entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CmsMenus extends \model\entities\CmsMenus implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'id', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'menuTitle', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'menuLink', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'menuOrder', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'status', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'menuType');
        }

        return array('__isInitialized__', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'id', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'menuTitle', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'menuLink', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'menuOrder', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'status', '' . "\0" . 'model\\entities\\CmsMenus' . "\0" . 'menuType');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CmsMenus $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuTitle($menuTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuTitle', array($menuTitle));

        return parent::setMenuTitle($menuTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuTitle', array());

        return parent::getMenuTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuLink($menuLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuLink', array($menuLink));

        return parent::setMenuLink($menuLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuLink', array());

        return parent::getMenuLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuOrder($menuOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuOrder', array($menuOrder));

        return parent::setMenuOrder($menuOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuOrder', array());

        return parent::getMenuOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuType(\model\entities\CmsMenuType $menuType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuType', array($menuType));

        return parent::setMenuType($menuType);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuType', array());

        return parent::getMenuType();
    }

}
