<?php

namespace model\entities\proxy\__CG__\model\entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BlogEntry extends \model\entities\BlogEntry implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'id', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryId', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryTitle', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryCover', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryAuthor', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entry', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'status', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'dateCreated', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryCategory');
        }

        return array('__isInitialized__', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'id', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryId', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryTitle', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryCover', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryAuthor', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entry', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'status', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'dateCreated', '' . "\0" . 'model\\entities\\BlogEntry' . "\0" . 'entryCategory');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BlogEntry $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntryId($entryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntryId', array($entryId));

        return parent::setEntryId($entryId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryId', array());

        return parent::getEntryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntryTitle($entryTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntryTitle', array($entryTitle));

        return parent::setEntryTitle($entryTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryTitle', array());

        return parent::getEntryTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntryCover($entryCover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntryCover', array($entryCover));

        return parent::setEntryCover($entryCover);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryCover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryCover', array());

        return parent::getEntryCover();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntryAuthor($entryAuthor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntryAuthor', array($entryAuthor));

        return parent::setEntryAuthor($entryAuthor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryAuthor', array());

        return parent::getEntryAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntry($entry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntry', array($entry));

        return parent::setEntry($entry);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntry', array());

        return parent::getEntry();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($dateCreated));

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntryCategory(\model\entities\BlogEntryCategory $entryCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntryCategory', array($entryCategory));

        return parent::setEntryCategory($entryCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryCategory', array());

        return parent::getEntryCategory();
    }

}
